name: blood_donation
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.2
  flutter_onboarding_slider: ^1.0.11
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^8.0.1
  shared_preferences: ^2.3.2
  multi_select_flutter: ^4.1.3
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  equatable: ^2.0.5
  image_picker: ^1.1.2
  file_picker: ^8.1.3
  supabase_flutter: ^2.8.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  rating_summary: ^1.0.3+1
  intl: ^0.19.0
  bottom_navy_bar: ^6.1.0
  google_maps_flutter: ^2.10.0
  pinput: ^5.0.0
  workmanager:
  onesignal_flutter: ^5.1.2
  firebase_core:
  firebase_messaging:
  dio: ^5.7.0
  easy_url_launcher: ^0.0.7
  chewie: ^1.10.0
  video_player:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/
    - assets/images/choose/
    - assets/lang/
    - assets/splash/
    - assets/fonts/
    - assets/logo/
    - assets/images/recycle/
    - assets/images/hospital_images/
    - assets/video/
  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
    - family: "ibm"
      fonts:
        - asset: assets/fonts/ibm/IBMPlexSansArabic-Regular.ttf
    - family: "cairo"
      fonts:
        - asset: assets/fonts/cairo/cairo.ttf
